### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jusmat** [kirillshevch/chef-template#5]
Hi, 

Great work there. Any plans to update dependencies? Like `redisio` is not even available anymore, nginx is under chef community scripts. Would be great to have those updated

**Comment by kirillshevch** [comment]
Hi @jusmat 
redisio moved to https://github.com/brianbianco/redisio
I'll try to fix reference as soon as possible

**Comment by jusmat** [comment]
I see. But ai do think that it would be good to update all berk dependencies to the newest. Current ones doesnt even seem to work for me on ruby 2.4.0

**Comment by kirillshevch** [comment]
Some updates in https://github.com/kirillshevch/chef-template/pull/6 https://github.com/kirillshevch/chef-template/pull/7 https://github.com/kirillshevch/chef-template/pull/8 https://github.com/kirillshevch/chef-template/pull/9

Also updated article https://medium.com/@kirill_shevch/using-chef-and-capistrano-to-deploy-rails-application-on-ubuntu-16-04-fae1dfe0dd12
